### PR TITLE
Add width property to Button component

### PR DESCRIPTION
**Pull request by tyruk**
This is a very simple change that allows define width property of Button component.

### CODE REVIEW

**Comment by ngarnier** [comment]
hey @tyruk, 

Can you please provide tests showing the compatibility of the `button` width property for MJML's list of [supported email clients](https://mjml.io/faq#email-clients)? You can use [Litmus](https://litmus.com/) or [Email on Acid](https://www.emailonacid.com/).

If it is indeed supported by all, we will merge it; if not, we won't be able to merge it.

**Comment by Tlapi** [comment]
I did a test before, and it looks good: https://github.com/mjmlio/mjml/issues/179

I think it is ready to merge.

**Comment by Tlapi** [comment]
Hey @ngarnier , what do you think? I think it is good to merge. @iRyusa ?

**Comment by ngarnier** [comment]
Hey @Tlapi, thanks for your previous answer and the tests you have done. I have some good news for you, @iRyusa is working on a refactor of the button that will introduce support for width on mj-button!

Thanks again for your contribution!

**Comment by iRyusa** [comment]
Hi @tyruk !

I'm sorry to close this PR, it was a bit more complex to add `width` and `height` on `mj-button` but it's now available in MJML3 !

**Pull request closed without merging**
