### PR TITLE
Add mjml-preset package

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/mjmlio/mjml/issues/1947#issuecomment-647006838

The new package includes all components and validations extracted from
main mjml package.

Now mjml-cli can be migrated into mjml package to reduce complexity a
little bit.

mjml-preset has `registerPreset` function which modifies global objects
by calling registerComponent and registerDependencies. Though there
might be a better and less side effectful way to define presets.

### CODE REVIEW

**Comment by TrySound** [comment]
I'm not a fan of "Prefer default export" lint rule. Not sure how to fix yet.

**Comment by iRyusa** [comment]
Really like it, it's way easier to use mj core without mj cli with that preset 👍 Can we wait a bit to finish MJML 4.7 before merging this?

**Comment by DRoet** [comment]
any ETA on the 4.7 release? really looking forward to the 5.x stuff that @TrySound is proposing

**Comment by TrySound** [comment]
Btw, maybe better provide declarative structure which is passed to mjml core instead?

**Comment by DRoet** [comment]
@TrySound could you try and give a small example of what you are suggesting?

**Pull request closed without merging**
