### PR TITLE
Support width="auto" on mj-column

### PR DESCRIPTION
**Pull request by caseyjhol**
Addresses #2144 

Code used to test:

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column width="250px" background-color="blue">
        <mj-button>250px</mj-button>
      </mj-column>
      <mj-column width="auto" background-color="red">
        <mj-button>auto</mj-button>
      </mj-column>
      <mj-column width="auto" background-color="yellow">
        <mj-image src="https://mjml.io/assets/img/logo-small.png" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Tested in:
Outlook 365
Outlook 2007
image
Gmail
image
Yahoo webmail
image
Outlook webmail
image

### CODE REVIEW

**Comment by caseyjhol** [comment]
@iRyusa Thoughts?

**Comment by iRyusa** [comment]
I have COVID so I'll try to play a bit with it when I'm back. I have few case in mind that we should test

**Comment by iRyusa** [comment]
Ok so I've played with it a bit and here a real use-case that doesn't work : 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column width="150px" background-color="blue">
        <mj-button>250px</mj-button>
      </mj-column>
      <mj-column width="auto" background-color="yellow">
        <mj-image src="http://via.placeholder.com/640x360" />
      </mj-column>
      <mj-column width="100px" background-color="red">
        <mj-button>auto</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Can't share the litmus test but it overflow on almost every clients. I don't know if there's a way to prevent that and if other component could just overflow the max-width too. It's not really a safe option (adding potential issue and confusion to user+ extra support on slack)

**Comment by caseyjhol** [comment]
For reference, this is the above example:

Chrome:
image

Outlook 2007:
image

I'll do some more investigating.

**Comment by iRyusa** [comment]
Closing for now as it's stale feel free to reopen if you find some way to prevent this.

**Pull request closed without merging**
