### PR TITLE
Mjml navbar

### PR DESCRIPTION
**Pull request by Aenohe**
- Add mjml-navbar component
  - Add mjml-inline-links component
  - Add mjml-link component

Standard Desktop:

<p align="center">

</p>

Standard Mobile:

<p align="center">

</p>

Mode hamburger enabled:

<p align="center">

</p>

Standard Test:

```
  <mjml>
    <mj-body>
      <mj-navbar full-width="full-width" background-color="#ef6451">
        <mj-column width="20%">
          <mj-image width="150px" src="https://mjml.io/assets/img/logo-white-small.png">
        </mj-column>
        <mj-column width="79%">
          <mj-inline-links base-url="https://mjml.io">

            <mj-link href="gettings-started-onboard" color="#ffffff">Getting started</mj-link>
            <mj-link href="try-it-live" color="#ffffff">Try it live</mj-link>
            <mj-link href="templates" color="#ffffff">Templates</mj-link>
            <mj-link href="components" color="#ffffff">Components</mj-link>
            <mj-link href="documentation" color="#ffffff">Documentation</mj-link>

          </mj-inline-links>
        </mj-column>
      </mj-navbar>
    </mj-body>
  </mjml>
```

Hamburger Test:

```
  <mjml>
    <mj-body>
      <mj-navbar full-width="full-width" background-color="#ef6451">
        <mj-column width="20%">
          <mj-image width="150px" src="https://mjml.io/assets/img/logo-white-small.png">
        </mj-column>
        <mj-column width="79%">
          <mj-inline-links base-url="https://mjml.io" hamburger="hamburger" ico-color="#ffffff">

            <mj-link href="gettings-started-onboard" color="#ffffff">Getting started</mj-link>
            <mj-link href="try-it-live" color="#ffffff">Try it live</mj-link>
            <mj-link href="templates" color="#ffffff">Templates</mj-link>
            <mj-link href="components" color="#ffffff">Components</mj-link>
            <mj-link href="documentation" color="#ffffff">Documentation</mj-link>

          </mj-inline-links>
        </mj-column>
      </mj-navbar>
    </mj-body>
  </mjml>
```

### CODE REVIEW

**Comment by dalefish** [comment]
Nice, was reading up on hamburgers in email just yesterday so thanks for this.

**Comment by Aenohe** [comment]
You're welcome. I hope this helps you.

**Comment by lohek** [comment]
👌

**Comment by jitendravyas** [comment]
Is this supported on all email clients MJML support?

**Pull request merged**
