### PR TITLE
Correct text color when parent has color too

### PR DESCRIPTION
**Pull request by meriadec**
see https://mjml.io/try-it-live/31f19dee07b3a16ac1b0

### CODE REVIEW

**Comment by meriadec** [comment]
tl;dr here is the case:

```
mj-body (color: red)
  mj-text (color: blue)    ==> should be blue
  mj-text                  ==> should be red
```

but actually, we can't check if color has been set or not, because [color is always set in default attributes](https://github.com/meriadec/mjml/blob/579ee54b52180776b730827da5b46ef475c19d01/src/components/Text.js#L14). So in which case should component take color from parent / from its attributes?

**Comment by iRyusa** [comment]
So maybe we need to change how `mjAttribute` works, now default attribute should stay at `state.elem.defaultAttribute` and 

```
mjAttribute(name) {
      return_.filter([this.props[name], this.state.getIn(['elem', 'attributes']).get(name), this.state.getIn(['elem', 'defaultAttributes']).get(name) ], function(e){ return e != undefined })[0] 
}
```

**Comment by meriadec** [comment]
If you are ok with this solution, I'll update `Button`, `Social` and `List` to have `color` in `defaultAttributes` instead of `attributes`

**Comment by meriadec** [comment]
closing this, not accurate anymore with current mjml engine

**Pull request closed without merging**
