### PR TITLE
Add text-transform on mj-text component

### LINKED ISSUE #131: MJ-TEXT Component missing 'text-transform' attribute!?
Was this by design (i.e. is there something I am overlooking where you can pass arbitrary "overrides" to the style attribute prior to HTML generation) or was this particular attribute just overlooked?

All the best,
-Skyler

### PR DESCRIPTION
**Pull request by pixelize**
Close #238
Fix #131

### CODE REVIEW

**Comment by iRyusa** [comment]
Hi @pixelize can you test it on litmus ?

**Comment by pixelize** [comment]
Hi @iRyusa, sure gonna do this afternoon. Campaign monitor says it's fully supported

http://www.campaignmonitor.com/css.

Will come back to you asap with results;)

**Comment by pixelize** [comment]
I just have a free account on Litmus, looks great on Outlook 2k13, Gmail & iPhone 6s. Based from that point and considering campaign monitor support, can we imagine to include this PR or do we need full design tests ?

**Comment by lohek** [comment]
Ok for me, @iRyusa ?

**Pull request merged**
