### PR TITLE
Increase the line height in mj-button so charachters are not cut off on multiline buttons

### PR DESCRIPTION
**Pull request by rogierslag**
We just received work that on some email clients the text on buttons would be slightly cut off

example

Since this obviously looks bad, I quickly dove into this, and as it turns out a slight additional line-height is required (font-size and line-height do not match up exactly). By increasing this from 100% to 120% the issues are resolved (under multiple fonts)

Litmus test: https://litmus.com/checklist/emails/public/799bfc8

### CODE REVIEW

**Comment by rogierslag** [comment]
References https://github.com/mjmlio/mjml/issues/319

**Comment by iRyusa** [comment]
Hi @rogierslag 

Sorry for the wait, can you provide a quick MJML to reproduce the issue with multiline button ?

The PR looks fine to me should we add a `mj-attribute` for `line-height` tho ?

**Comment by rogierslag** [comment]
No problem.

You can check an example of the mjml at https://mjml.io/try-it-live/Syb7kQQFl

I agree with your suggestion, lets make the line-height customisable (since it also depends on how the font works exactly). A one size fits all will probably conflict for some users. As a default value, I suggest to keep it 120% to allow for a bit more spacing (this also makes the button better tappable on mobile devices)

**Comment by rogierslag** [comment]
Build failure on an unrelated dangling comma

**Comment by iRyusa** [comment]
Hi @rogierslag

Coming back to this, we're testing the new `mj-button` in #557 and if it's still an issue we'll ping back here to know if you can update the PR for it.

**Comment by rogierslag** [comment]
👍

**Comment by iRyusa** [comment]
Hi @rogierslag 
Fix is still needed, however we don't want to force any default unit on `line-height`. Would you want to update your PR or I can apply this PR #658 and credit you for the line-height in the changelog ?

**Comment by rogierslag** [comment]
The latter option was fine! Sorry, but swamped with work :'(

**Pull request closed without merging**
