### PR TITLE
Fix broken links in README.md

### PR DESCRIPTION
**Pull request by webtaculars**

### CODE REVIEW

**Comment by webtaculars** [comment]
Contribute link is also broken. There is no issue with the version 3.3.x but in MJML 4, these links were not taken care. Can you help me in fixing that link too?

**Comment by ngarnier** [comment]
Thanks @webtaculars!

**Comment by webtaculars** [comment]
@ngarnier Contribute link is also broken. Can I help in fixing that too?

**Comment by ngarnier** [comment]
Of course, if you see any link that needs to be updated, or any documentation generally, your help is much appreciated!

**Pull request merged**
