### PR TITLE
Allow padding on mj-container component

### LINKED ISSUE #204: How do you set document/mj-body gutter ?
Hey guys,

Just started my first email with MJML which looks a good framework.
Otherwise, I'd like to set a left and right gutter outside my general template. In fact, i'd like to add a padding-left and padding-right to the body so my container has spaces on the sides.

group 3

I tried several things like putting in additional mj-column, settings padding on mj-body or wrapping with a mj-section but nothing works. Any help would be very appreciated ;)

Keep up the good work.

Here is my code : [http://codepen.io/Pixelize/pen/qZJWyd](http://codepen.io/Pixelize/pen/qZJWyd)

(sorry but github code tag is totally bugging)

### PR DESCRIPTION
**Pull request by pixelize**
Fix #204 #160

### CODE REVIEW

**Comment by iRyusa** [comment]
Hello @pixelize 
`padding` is supported only on `td` and `p` for every client that's we can't add it on the container
And it could break so many thing that being computed from container's width

**Comment by pixelize** [comment]
Hey @iRyusa, it's not working on p or div on Outlook clients right ? Does it matter if we can apply it anyway and accept that will not not rendered in Outlook but in others email/web clients ?
Just did some test on Litmus, my test layout was ok on these ! Btw, you're more expert than me in css properties support in email clients, it's up to you 👍

**Comment by ngarnier** [comment]
Hey @pixelize, we really appreciate your PR, thanks for contributing!

Unfortunately, as @iRyusa said, merging this would lead to too many uncontrolled issues. We want MJML to be responsive and supported on every major email clients, which includes Outlook, without requiring users to dig in what works and what doesn't for each email clients. 

I hope it makes sense to you and hope to have more contributions from your side, glad to have you onboard!

**Comment by pixelize** [comment]
Happy to help such a great project !
No problem, I totally agree with you. Good to know of you want MJML to be driven, will keep in mind for next PR :)

**Pull request closed without merging**
