### PR TITLE
mj-button > Added attribute and edited readme for text-transform

### PR DESCRIPTION
**Pull request by jitendravyas**

### CODE REVIEW

**Comment by ngarnier** [comment]
Hey @jitendravyas, thanks for your PR. Can you also please update the [Readme.MD](https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/README.md) so it is documented?

**Comment by jitendravyas** [comment]
Sure, Will do it now

**Comment by iRyusa** [comment]
Hi @jitendravyas can you update the documentation on the same branch so we can close #272 and merge this one ? thanks

**Comment by jitendravyas** [comment]
I didn't get what do mean by documentation on same branch?

**Comment by iRyusa** [comment]
You've opened 2 different PR for documentation and the attribute you have merge your work into one single branch + PR

**Comment by jitendravyas** [comment]
oh ok for that I think I have to clone this project in my laptop and send pull requests from there. On github I think it creates new branch for every file chanfe

**Comment by jitendravyas** [comment]
@iRyusa I have merged

**Pull request merged**
