### PR TITLE
add cross-env to all command for cross platform dev:

### PR DESCRIPTION
**Pull request by f3ltron**
add cross-env packages for dev in multiplatform because '..' is not recognized on windows 10

### CODE REVIEW

**Comment by iRyusa** [comment]
Hi @f3ltron 

Thanks for this PR ! Can you just remove the package.json.lock : we only use yarn.lock in this project

**Comment by f3ltron** [comment]
sure i do it this day

**Comment by iRyusa** [comment]
Hey @f3ltron !

Any news on this ? :)

**Comment by f3ltron** [comment]
oh yeah i totally forget !! I do it today or tomorrow sorry ^^

**Comment by duttaditya18** [comment]
@f3ltron Can you please follow up?

**Comment by iRyusa** [comment]
Closing because #1091 did the same 

Thanks for the pr !

**Pull request closed without merging**
