### PR TITLE
Fix mjml-button text display on older outlook versions

### LINKED ISSUE #385: button text not displayed on older outlook versions
Hi,

Thank you for this awesome tool !

## Description : 
When using an mj-button like the one provided here : https://mjml.io/try-it-live/components/button/
The text does not display on some email clients.
To find this bug, I simply pasted the HTML provided by the try it live platform on Litmus, without changing anything. And the text did not display on some clients. (I add this problem on my application too so I was trying to reproduce it with the simple version of the example)

The version I'm using is 2.3.1

### Supported :
- Outlook 2000
- Outlook 2002
- Outlook 2003

### Not supported :
- IBM Notes 9
-  Lotus Notes 8.5

## Possible solution
The text is actually displayed if the property display:inline-block is removed from the a tag of the email. I have not seen any other side effect on my litmus test when removing this property (but I can't be sure what it is supposed to do). I tried to remove the display clause and to play with the attribuets of the mj-button tag and eveything worked fine.

### PR DESCRIPTION
**Pull request by Uelb**
By removing the display:inline-block property

Fix #385

### CODE REVIEW

**Comment by iRyusa** [comment]
Well `line-height:100%` still crop the text on outlook 2003 :/

2003:
ol2003-vertical-allowed-1366

2007
ol2007-vertical-allowed-1366

**Comment by Uelb** [comment]
With this code : 
````html
<td style="color:#ffffff;cursor:auto;padding:10px 25px;" align="center" valign="middle" bgcolor="blue">
                                <a href="http://mjml.io" style="text-decoration:none;background:transparent;color:#ffffff;font-family:Helvetica;font-size:13px;font-weight:bold;color:white;margin:0px;font-style: italic; line-height:100%;display:inline-block;" target="_blank">
									Don't click me! Cause I'm super radioactive... So ? What do you say ?
                                </a>
                              </td>
````
On litmus, it works fine for with a multine button

**Comment by Uelb** [comment]
[https://ol2003.capture.litmuscdn.com/c45f651a-678f-4cd0-a26c-cea91acf5216/results/ol2003-vertical-allowed-1366.png]

**Comment by iRyusa** [comment]
My bad ! it 's ok on master, it was an issue with new feature on the validation branch I fixed it

**Pull request merged**
