### PR TITLE
feat: Add middleware (preprocessors) to mjml parser

### LINKED ISSUE #42: Handlebars tag support (used by mandrill)
Hello,

Mandrill and Mailchimp support Handlebars template syntax, could we imagine a command like ```mjml -r template.mjml -o template.html --syntax=handlebars``` or ```mjml -r template.mjml -o template.html --syntax=mailchimp``` ? 

Example:

replacement_html_ __users_romainnorberg_documents_jobs_web_calendrier_fonctionnel_web_template_mail

Links:
* http://handlebarsjs.com/
* http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html

Thank u, Mjml is great!

### LINKED ISSUE #457: Twig tags in my MJML file
I'm hoping to use MJML to create some email templates for my website powered by Craft. Craft uses Twig as its templating language. Instead of coding static content into my MJML templates I'm hoping to leave in my Twig tags.

My issue is this. When I use twig's output tags like `{{ siteurl }}` it works as aspected. But when I use logic tags like `{% set posts = craft.entries.section('blog') %}` it seems to strip those out completely. I need to escape these tags so that they stay in.

Is there anything I can configure to make these tags not get removed?

### LINKED ISSUE #874: dynamic replacing content for mj-include with handlebars
Hi, 

I tried running my mjml file trough handlebars compile function to replace the content, but it is not able to reach into `<mj-include />` and replace the template tags there.

So is there a way to "render" the include file in mjml and still keep it as `.mjml` or similar? or make handlebars reach into the `<mj-include/>` file?

Thanks

### PR DESCRIPTION
**Pull request by XBeg9**
Closes #42
Fixes #874
Fixes #457

This pull request adds a preprocessors feature to mjml parser. From now on, you can pass `preprocessors` as an option to MJMLParser to preprocess XML before it will generate final HTML elements.

```javascript
MJMLParser(mjml, {
    keepComments: true,
    components,
    preprocessors: [
      data =>
        template(data)({
          buttons: [{ title: 'Title' }, { title: 'Title2' }],
        }),
    ],
  })
```

Each middleware has such `(xml: string) => string;` interface. This code also works when you do `<mj-include pathh="other.mjml" />`.

Test file: `node packages/mjml-parser-xml/test/test-preprocessors.js`

### CODE REVIEW

**Comment by XBeg9** [comment]
Probably, it also fixes #459

**Comment by vtereshyn** [comment]
Please, let's merge that. We also really need this fix!

**Comment by iRyusa** [comment]
The feature looks great i'm not sure about the middleware naming, pre-processor might suits better here ?

**Comment by XBeg9** [comment]
@iRyusa I was also struggling around naming :) preprocessors sounds good to me. Changing.

**Comment by XBeg9** [comment]
@iRyusa due to the way you made this repo, there is no way to install the package from the feature branch (lerna + babel). Will you be able to make a release after the merge? Thanks

**Comment by iRyusa** [comment]
I should have some spare time next week to merge this & merge my own modifications on mj-column.

Will try to sync with @kmcb777 to merge his patch too and we should be able to release it :)

**Comment by iRyusa** [comment]
@kmcb777 I'll let you give a 2nd review and we'll merge it then

**Comment by XBeg9** [comment]
any updates? @iRyusa @kmcb777

**Comment by iRyusa** [comment]
@kmcb777 was in holiday, he should be back tomorow. I  won't have any time for review because of family issue but it should be OK to merge in 4.6 for  me

**Comment by XBeg9** [comment]
Hi @iRyusa, thanks for the merge. Will you publish new version npm? Thanks

**Comment by iRyusa** [comment]
Yup we're working on it will be available on 4.6

**Comment by charanjit-singh** [comment]
Will it work to generate tags in django. I don't want to preprocess and insert data, I want to add tags into the generated HTML which will be used by jinja template.

**Pull request merged**
