### PR TITLE
Setup yarn workspaces

### PR DESCRIPTION
**Pull request by TrySound**
Yarn workspaces simplify upgrading dependencies, for example with
`yarn upgrade-interactive --latest` command.

Also easier to track what's in node_modules.

### CODE REVIEW

**Comment by iRyusa** [comment]
Had a quick review this seems nice, I think we can merge that after 4.6 ?

**Comment by TrySound** [comment]
I wanted to submit a couple of more PRs. For example with migrating to babel 7 without core-js dependency.

**Comment by iRyusa** [comment]
That would be great ! Feel free to ping me on slack if you need anything

**Comment by TrySound** [comment]
@iRyusa Looks like errors came from other committer.
image

**Comment by iRyusa** [comment]
Yup @kmcb777 will fix it soon sorry about that

**Comment by TrySound** [comment]
@iRyusa I rebased. Looks like no-unresolved lint is fixed with yarn workspaces. Good to merge?

**Pull request merged**
