### PR TITLE
mjml-section > Added border radius for section and updated readme

### PR DESCRIPTION
**Pull request by jitendravyas**

### CODE REVIEW

**Comment by iRyusa** [comment]
Hello @jitendravyas can you update the documentation to reflect this change ? thanks

**Comment by jitendravyas** [comment]
Done https://github.com/mjmlio/mjml/pull/288

**Comment by ngarnier** [comment]
Hey @jitendravyas, have you tested this locally? Can you provide tests/screenshots as stated in the [Contributing.md](https://github.com/mjmlio/mjml/blob/master/CONTRIBUTING.md), at least for email clients available on free accounts?

**Comment by jitendravyas** [comment]
@ngarnier This is just a border-radius which doesn't add any extra pixel to box-model so it won't create any problem for the client which doesn't support it and it work fine with whichever email supports it. I have used border-radius in email

**Comment by iRyusa** [comment]
I have tested it, and border-radius isn't applied because `table` has a `border-collapse:collapse;` so `radius` will be ignored

**Comment by iRyusa** [comment]
As mentioned earlier : 

> I have tested it, and border-radius isn't applied because table has a border-collapse:collapse; so radius will be ignored

So I'm closing this PR atm, thanks for your contribution @jitendravyas

**Comment by tomgenoni** [comment]
To add `border-radius` to a section it must be applied to both the table *and* its parent `<div>`. `border-collapse: collapse` does not appear to affect it. See https://jsfiddle.net/7q5g8z39/

**Comment by iRyusa** [comment]
@tomgenoni nice find ! I'll try to add this on a next release

**Comment by tomgenoni** [comment]
Thank you! This is a great project, appreciate all your work on it.

**Pull request closed without merging**
