### PR TITLE
Make section alignable

### PR DESCRIPTION
**Pull request by thomaschaaf**
Currently all emails are centered. I would like to send emails which are not centered.

I have attached screenshots for this mjml code.
```
<mjml>
  <mj-body>
    <mj-section align="left">
      <mj-column>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

### CODE REVIEW

**Comment by ngarnier** [comment]
Hey @thomaschaaf, thanks for this PR. 

Can you please explain the use-case? It's not very clear to us and we're a bit afraid of issues that could be caused by this PR. Example: I just tried having 2 sections with one left-aligned and one right-aligned and it produces this:

**Comment by ngarnier** [comment]
This was merged by mistake and reverted

**Comment by thomaschaaf** [comment]
@ngarnier why not use the revert merge from github? I have now created a new pr.

**Comment by ngarnier** [comment]
I was waiting for your feedback on the comments + question @thomaschaaf. Let's now keep it on the new PR you opened then.

**Pull request merged**
