### PR TITLE
Conditional comment for Outlook

### PR DESCRIPTION
**Pull request by rojasmi1**
Now conditional comments for Outlook work for versions older than Outlook 2007 and for Lotus Notes 8. Outlook 2003 and older don't recognize the [if mso] condition, but since they use IE as the pre-renderer adding the [if mso | IE] condition will make the responsive table-based layout work for all Outlook versions and for Lotus Notes 8.

If you think this is not correct or if it needs some additional changes let me know, I tested it with Litmus and it works just fine.

### CODE REVIEW

**Comment by dalefish** [comment]
This may also address this single column issue with 2003.

Ref: https://github.com/mjmlio/mjml/issues/40

**Comment by dalefish** [comment]
Tested this theory against one of my existing builds, seems to fix the single column issue on <= 2003

**Comment by lohek** [comment]
Ok for me, cc @iRyusa

**Comment by iRyusa** [comment]
Hi,
this PR has conflicts, can you resolve them before merging ? thanks

**Comment by rojasmi1** [comment]
@iRyusa Thanks for taking a look, I will resolve the conflicts as soon as I have time and access to the code.

**Comment by ngarnier** [comment]
Hey @rojasmi1, do you have an idea of when you'll be able to resolve conflicts? We'd really want to merge this!

Thanks again for your contribution.

**Comment by rojasmi1** [comment]
@ngarnier Hi Nicolas, I'm sorry for the delay! I had some problems these days but today I will have some time to do it. Thanks for the reminder.

**Comment by rojasmi1** [comment]
@ngarnier Hey Nicolas, I just merged my changes with the latest changes on your master repo! This is the first time that I'm doing a Pull Request so please let me know if there is anything wrong.

**Comment by ngarnier** [comment]
Awesome, thanks @rojasmi1!

**Comment by lohek** [comment]
👌 thanks !

**Pull request merged**
