### PR TITLE
fix-1765 remove comment from second block of mj-hero MJML code

### PR DESCRIPTION
**Pull request by GarryFlemings**
Issue #1765

### CODE REVIEW

**Comment by 2dareis2do** [comment]
why is this still open?

**Comment by 2dareis2do** [comment]
One thing  I noticed that on the hero documentation it mentions the width property is available, but my IDE informs me that it is not.

**Comment by GarryFlemings** [comment]
@2dareis2do Your IDE is correct; &lt;mj-hero&gt; doesn't include a _width_ attribute.

I just filed PR#1795 addressing documentation for &lt;mj-text&gt;. I'll work on a similar PR for &lt;mj-hero&gt; next. Thanks for noticing and commenting. 🙏

I'll leave this PR for the original scope. I inadvertently applied this PR to _master_ rather than _next_. 👎 I suspect that, too, is a major challenge in this remaining open. Fixing that tonight.

**Comment by GarryFlemings** [comment]
This PR is erroneously applied to mjmlio:master. Closing to resubmit.

Resubmitted as commit 1dfd182d in PR#1764.

**Pull request closed without merging**
