### PR TITLE
feat: drop node 8 and use github actions

### PR DESCRIPTION
**Pull request by DRoet**
see https://github.com/mjmlio/mjml/pull/1907#issuecomment-629800846

Thought it would be interesting to use the builtin github actions instead since it is pretty neat, but I can revert that change if needed.

successful run on my fork: https://github.com/DRoet/mjml/actions/runs/107366295
successful run with 14.x included: https://github.com/DRoet/mjml/actions/runs/110149142

### CODE REVIEW

**Comment by DRoet** [comment]
@iRyusa I added node 14.x aswell since it will become the next LTS in october

**Comment by DRoet** [comment]
OK this should be ready to be merged now

**Comment by iRyusa** [comment]
Probably need to remove the travis badge then on readme ?

**Comment by DRoet** [comment]
@iRyusa done

**Comment by iRyusa** [comment]
Looks like we have a yarn lock conflict then we could merge that I think, we'll monitor if the free tier isn't enough then we'll rollback to travis I guess

**Comment by DRoet** [comment]
@iRyusa fixed.

GitHub Actions usage is free for public repositories, I don't believe there are any limits to it currently, but I might be unaware.

**Comment by DRoet** [comment]
@iRyusa After landing https://github.com/mjmlio/mjml/commit/5250617520c790252202a14d77fa53bb28f15e52

The build in this PR actually runs, CI is still green 😃

**Pull request merged**
