### PR TITLE
Fix and remove mj-image default css width

### PR DESCRIPTION
**Pull request by Tlapi**
There is no reason to add 100% default css width

### CODE REVIEW

**Comment by iRyusa** [comment]
Hi @Tlapi !

I'd prefer to keep the image 100% to avoid the overflow. I'd rather add a `width` on `td` to keep a safety for big images. Does it make sense to you ?

**Comment by Tlapi** [comment]
Hey @iRyusa,

if you want to avoid overflow, set max-width. But now, when you set width of image to something less then 100%, it gets ignored, as css inline style is prefered over width attribute.

**Comment by iRyusa** [comment]
`Max-width` is a pain see #86 :/

`Width` attribute is only here for Outlook that doesn't support `style width` for `img`
Adding the width on the `td` should solve your issue since the 100% will match the container

**Comment by Tlapi** [comment]
Ok, i have checked and tested, seems fine to set `width` attribute on `td`. I will close this PR and open a new one.

**Comment by Tlapi** [comment]
Uhm, this gets a bit messy. So i will leave that up to you to keep your standart.

**Comment by janus-reith** [comment]
No it is not fine.
Before i could simply set the width of my image to 560px, achieving 20px padding at each side, while still having the full width on mobile view.

Setting the column width to 560px breaks the mobile view as it will not scale anymore.
Adding 20px padding to the image will also make it way smaller in mobile view.

Adding the ability of mobile/desktop only styles could be a better long term solution...
Using mj-raw everytime I need the is a bit messy

**Comment by iRyusa** [comment]
> Adding the ability of mobile/desktop only styles could be a better long term solution... 
Fact is, no so much email clients supports media queries. A PR will be open shortly to fix the width issue

**Pull request closed without merging**
