### PR TITLE
Make the entire button clickable if a href is set

### PR DESCRIPTION
**Pull request by rogierslag**
Closes https://github.com/mjmlio/mjml/issues/359

https://litmus.com/builder/24aaa37 shows the button is kept everywhere (I cant test whether its really rendered properly as a link, but at least the button does not disappear)

Flyby: fixed the eslint for the mj-button file

### CODE REVIEW

**Comment by rogierslag** [comment]
Updated the link in the PR description

**Comment by iRyusa** [comment]
I'm not a big fan of nesting anchor inside an anchor (and it's not valid from an html standpoint https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element).

**Comment by rogierslag** [comment]
Me neither, but the upside is that if the outer anchor does not work it will "gracefully" degrade to the current behaviour. For clients which do support it, it will ensure the entire button is a clickable area

**Comment by iRyusa** [comment]
Many clients can behave unexpectedly with nested anchor, so I can't merge this.

Maybe there's a better implementation of mj-button... put every style inside the `a` and make a table based button for outlook, but it will add overhead to the HTML...

**Comment by vbraun** [comment]
The post at https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design seems to be a good overview over the situation. Currently mjml uses 2) but it seems that 4) would be optimal. Also, it would not be that much of a change over the current html structure. Thoughts?

**Comment by rogierslag** [comment]
Ok properly fixed now. See litmus tests [here](https://litmus.com/builder/053802d)

This should be ready for merge :)

**Comment by iRyusa** [comment]
hi @rogierslag 

Can you provide a litmus document with this markup ?

```xml
 <!-- Start of button -->
      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="white" background-color="#f45e43" font-style="italic">
            Background-color & font-size
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="white" background-color="#f45e43" border-radius="50px">
            border-radius
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" font-size="18px" color="black" background-color="#FFFFFF" align="right">
            align right
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" font-size="18px" color="black" background-color="#FFFFFF" align="left">
            align left
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="white" background-color="#f45e43" border="2px solid #FFF" vertical-align="top">
            2px solid #FFF
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="white" background-color="#f45e43" border="2px dashed #FFF" vertical-align="bottom">
            2px dashed #FFF
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#4d4d4d" background-color="#f45e43" container-background-color="#FFF" padding="35px 10px">
            container-background-color & padding
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#333" border="solid 2px #f45e43" border-radius="20px" background-color="transparent" inner-padding="15px 30px">
            Ghost button
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
          <mj-column>
            <mj-button href="https://mjml.io/" font-family="Helvetica" color="#333" border-top="solid 2px #f45e43" border-bottom="solid 2px #f45e43" background-color="transparent" inner-padding="15px 30px">
              Border-top, border-bottom, transparent
            </mj-button>
          </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#333" border-left="solid 2px #f45e43" border-right="solid 2px #f45e43" border-radius="20px" background-color="#ddd">
            Border-left, border-right & radius
          </mj-button>
        </mj-column>
      </mj-section>


      <mj-section>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#333" border="solid 2px #f45e43" border-radius="20px" background-color="transparent" width="200">
            Width 200px
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#333" border="solid 2px #f45e43" border-radius="20px" background-color="transparent" height="80">
            Height 80px
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button href="https://mjml.io/" font-family="Helvetica" color="#ffffff" border="solid 2px #111" border-radius="20px" background-color="#f45e43" width="200" height="80">
            Height 80px & Width 200px
          </mj-button>
        </mj-column>
      </mj-section>
      <!-- Enf of button -->
```

**Comment by rogierslag** [comment]
No problem. Made one fix which I noticed was off (border would overwrite another property).

However, Outlook does not handle border properly (could not have guessed that). If the text within the button is too long and causing it to wrap to two lines, outlook applies the border separately on each line :\

https://litmus.com/builder/053802d

**Comment by rogierslag** [comment]
I have created the same email using the current `master` branch, and unfortunately that is definitely a regression. So please do not merge this

https://litmus.com/builder/eba28ff

**Comment by rogierslag** [comment]
Ok managed to fix it. The example for litmus is still at https://litmus.com/builder/053802d

**Comment by iRyusa** [comment]
There's a big regression on border radius buttons comparing to master branch and border+radius doesn't work too

screen shot 2016-12-14 at 17 50 23

**Comment by rogierslag** [comment]
Hmm supporting border-radius and outlook seems like quite a difficult task. I got something working but that reduces the button in Outlook 2010 and 2013 to tears

screenshot 2016-12-15 09 43 51
screenshot 2016-12-15 09 43 44

It might be doable by "fixing" it with a postRender, but will look into that later this week (I hope)

**Comment by jdotjdot** [comment]
Looking forward to seeing what you find.  We just ran into this issue and we're using images for our buttons instead for the time being, which is obviously not ideal.

**Comment by rogierslag** [comment]
I continued working on it on a separate branch https://github.com/mjmlio/mjml/compare/master...rogierslag:testing?expand=1 and now it looks like (this)[https://litmus.com/checklist/emails/public/0170152]

Some problems

- Outlook 2010 and 2013 show a crazy border
- vertical align does not work

However I have lost all track on how to fix these last point. The click regions work though.

I'm afraid the regression with relation to Outlook is too big to merge that branch now (so hence do not merge this one)

**Comment by jdotjdot** [comment]
There might be room here to take a completely different approach and use clickable images instead. Not ideal, but will likely be cross-client compatible for the most part.

An MJML component could be created (or an attribute on `<mj-button>` called `type="image"` or something like that) that uses a service like https://placehold.it/ to take the attributes that are passed in to style `<mj-button>` and translates them to an auto-generated identical-looking image, which will be contained within a `<a>` tag.

**Comment by rogierslag** [comment]
I also considered using VML but outlook does not really support nested rendering of those, and it's already being used in `mj-section`

**Comment by rogierslag** [comment]
Pretty sure https://github.com/mjmlio/mjml/pull/557 is a better solution that this TBH

**Comment by iRyusa** [comment]
Hi @rogierslag 

We're now testing #557 so I think we can close this PR for now ? Thanks for the lot of work you've put into this !

**Pull request closed without merging**
