### PR TITLE
Replace problematic chars with placeholders 

### PR DESCRIPTION
**Pull request by iRyusa**
Avoid Juice to goes on infinite loop, and Cheerio to misinterpret some tag-like chars

### CODE REVIEW

**Comment by iRyusa** [comment]
Will probably paste this in MJML4 if you're ok with this @lohek

**Comment by web-padawan** [comment]
Hi! Just curious: should this also allow using [SparkPost](https://developers.sparkpost.com/api/substitutions-reference.html#header-basic-substitution) templates? Is there any ETA on when will this be released?

**Comment by ngarnier** [comment]
hey @web-padawan, yes SparkPost templating syntax should work fine with this fix (let us know anything you find!). We'll release 3.3.1 today :)

**Comment by ngarnier** [comment]
Actually, due to an issue with NPM we can't publish today, sorry. Likely next week!

**Comment by web-padawan** [comment]
@ngarnier Thanks!

**Comment by web-padawan** [comment]
I've just upgraded to `3.3.2` and code like `{{if user.language=="ru"}}` or `{{each products}}` in text still gets stripped out when compiling, while inside of attributes it does not. 
Could you check that please?

**Comment by iRyusa** [comment]
Can you provide some code to reproduce please ?

**Comment by ngarnier** [comment]
Hey @web-padawan, you still need to add your templating snippets inside components such as `mj-text` or `mj-raw`, I think that's the issue.

**Comment by web-padawan** [comment]
UPD: looks like fixing #600 will resolve my issue.

**Pull request merged**
