### PR TITLE
Better productivity with SpeedyTag

### PR DESCRIPTION
**Pull request by martindebrunne**
Now we can use a fast similar slim tag. I named it SpeedyTag and i used .mjml.fit extension to distinct .mjml file. But that doesn't matter. You just need to use SpeedyTag format in a file. 
It's based on mjml tags. 
See files examples in test/assets.  You can use same commands lines to render a html file and give the right file.

### CODE REVIEW

**Comment by martindebrunne** [comment]
Should I change name extension in order to pass tests ?

**Comment by iRyusa** [comment]
Wow ! Looks really impressive :+1:

**Comment by ngarnier** [comment]
Hey @martindebrunne, 

Thanks for the PR, it's really interesting. Unfortunately, we can't merge it because it would mean a heavy dependency to `mjml-core`. 

A better approach would be to make it a plugin / tool around MJML, maybe with integrations in text editors such as Atom/Sublime Text? What do you think?

**Comment by martindebrunne** [comment]
Thank you for your reply. I think a tool around MJML can be nice and some plugins for text editors in order to 'check syntax and run the MJML tool' can be fine for the development and make easy the integration in a lot of text editors. 
When I will have time I will try to do it.

**Comment by ngarnier** [comment]
Hi, I'm closing this PR as it's based on a version of MJML which is very outdated. 

As discussed at the time, we've worked with the help of the community to reach a better productivity thanks to plugins and tools. Here are a few of the ones available:
- Atom packages: https://atom.io/users/mjmlio
- Sublime package: https://packagecontrol.io/packages/MJML-syntax
- Collection of tools (Vim plugin, Gulp, Grunt...): https://mjml.io/community

Thanks again!

**Pull request closed without merging**
