### PR TITLE
Add possibility between share and follow

### PR DESCRIPTION
**Pull request by Tlapi**
Update social.js and add possibility to choose between sharing url or just social follow.

### CODE REVIEW

**Comment by iRyusa** [comment]
Looks good to me :+1:

**Comment by Tlapi** [comment]
Cool, thank you.

**Comment by iRyusa** [comment]
Hi there @Tlapi , just want to follow up from your PR. We're adding possibility in `1.3` to switch between `share` and `follow` for each social network by adding a simple :url for each network as : 
`<mj-social display="twitter:url facebook google:url" ... />`.

What do you think about it ?

**Comment by Tlapi** [comment]
Looks good to me :+1:

**Comment by iRyusa** [comment]
As `1.3` is released, I close this !

**Pull request closed without merging**
